In [22]:
import numpy as np

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [24]:
np.argmax(a)

16

In [25]:
np.argmax(a[0:3])

2

In [26]:
a[3]

4

In [27]:
a[0:2], a[2:5], a[5], a[6:8], a[8:11], a[11], a[12:14], a[14:16]

(array([1, 2]),
 array([3, 4, 5]),
 6,
 array([7, 8]),
 array([ 9, 10, 11]),
 12,
 array([13, 14]),
 array([15, 16]))